#!/bin/bash

echo "🚀 WhyReboot GPT Support Setup Guide"
echo "====================================="
echo ""

echo "📋 Step 1: Slack App Configuration"
echo "----------------------------------"
echo "1. Go to https://api.slack.com/apps"
echo "2. Click 'Create New App' → 'From scratch'"
echo "3. Name: 'WhyReboot Support Bot'"
echo "4. Select your workspace"
echo ""

echo "🔑 Step 2: Configure Bot Permissions"
echo "-------------------------------------"
echo "1. Go to 'OAuth & Permissions' in left sidebar"
echo "2. Add these Bot Token Scopes:"
echo "   - search:read"
echo "   - channels:read" 
echo "   - groups:read"
echo "3. Click 'Install to Workspace'"
echo "4. Copy the 'Bot User OAuth Token' (starts with xoxb-)"
echo ""

echo "⚙️ Step 3: Update Environment Variables"
echo "--------------------------------------"
echo "Replace the SLACK_BOT_TOKEN in .env.local with your new token"
echo ""

echo "🌐 Step 4: Deploy to gpt.whyreboot.com"
echo "--------------------------------------"
echo "1. Push code to GitHub"
echo "2. Deploy to Vercel (recommended)"
echo "3. Add environment variables in Vercel dashboard"
echo "4. Configure custom domain: gpt.whyreboot.com"
echo ""

echo "✅ Step 5: Test the Integration"
echo "------------------------------"
echo "1. Visit gpt.whyreboot.com"
echo "2. Ask a question"
echo "3. Check if Slack context is found"
echo ""

echo "📞 Need Help?"
echo "-------------"
echo "- Check the SETUP_GUIDE.md file"
echo "- Test with: curl http://localhost:3000/api/health"
echo "- Monitor logs for any errors"
echo ""

echo "🎯 Current Status:"
echo "-----------------"
echo "✅ OpenAI API: Configured"
echo "❌ Slack Bot: Needs new token with proper permissions"
echo "✅ Support Channel: C09AEQV3KDK"
echo "✅ Application: Running on localhost:3000"
echo ""
